// A curated list of popular Google Fonts for the Storefront Studio font picker.
// Any of these can be applied to headings or body; StorefrontThemeProvider
// lazy-loads the chosen families via loadGoogleFont(). Grouped loosely so the
// picker can show a category hint. This is intentionally a broad-but-finite set
// (no network/API-key needed) covering the fonts merchants actually reach for.

export interface GoogleFont { family: string; category: 'sans' | 'serif' | 'display' | 'handwriting' | 'mono'; }

export const GOOGLE_FONTS: GoogleFont[] = [
  // ── Sans-serif ─────────────────────────────────────────────────────────
  { family: 'Inter', category: 'sans' },
  { family: 'Roboto', category: 'sans' },
  { family: 'Open Sans', category: 'sans' },
  { family: 'Lato', category: 'sans' },
  { family: 'Montserrat', category: 'sans' },
  { family: 'Poppins', category: 'sans' },
  { family: 'Nunito', category: 'sans' },
  { family: 'Nunito Sans', category: 'sans' },
  { family: 'Work Sans', category: 'sans' },
  { family: 'Manrope', category: 'sans' },
  { family: 'DM Sans', category: 'sans' },
  { family: 'Rubik', category: 'sans' },
  { family: 'Karla', category: 'sans' },
  { family: 'Mulish', category: 'sans' },
  { family: 'Quicksand', category: 'sans' },
  { family: 'Barlow', category: 'sans' },
  { family: 'Kanit', category: 'sans' },
  { family: 'Heebo', category: 'sans' },
  { family: 'Hind', category: 'sans' },
  { family: 'PT Sans', category: 'sans' },
  { family: 'Source Sans Pro', category: 'sans' },
  { family: 'Fira Sans', category: 'sans' },
  { family: 'Cabin', category: 'sans' },
  { family: 'Titillium Web', category: 'sans' },
  { family: 'Josefin Sans', category: 'sans' },
  { family: 'Assistant', category: 'sans' },
  { family: 'Figtree', category: 'sans' },
  { family: 'Plus Jakarta Sans', category: 'sans' },
  { family: 'Sora', category: 'sans' },
  { family: 'Space Grotesk', category: 'sans' },
  { family: 'Lexend', category: 'sans' },
  { family: 'Outfit', category: 'sans' },
  { family: 'Onest', category: 'sans' },
  { family: 'Albert Sans', category: 'sans' },
  { family: 'Schibsted Grotesk', category: 'sans' },
  { family: 'Instrument Sans', category: 'sans' },
  { family: 'Geist', category: 'sans' },
  { family: 'Hanken Grotesk', category: 'sans' },
  { family: 'Be Vietnam Pro', category: 'sans' },
  { family: 'Red Hat Display', category: 'sans' },
  { family: 'Overpass', category: 'sans' },
  { family: 'Urbanist', category: 'sans' },
  { family: 'Epilogue', category: 'sans' },
  { family: 'Jost', category: 'sans' },
  { family: 'Archivo', category: 'sans' },
  { family: 'Chivo', category: 'sans' },
  { family: 'Public Sans', category: 'sans' },
  { family: 'Libre Franklin', category: 'sans' },
  { family: 'IBM Plex Sans', category: 'sans' },
  { family: 'Readex Pro', category: 'sans' },
  { family: 'Anek Latin', category: 'sans' },
  { family: 'Gabarito', category: 'sans' },
  { family: 'Bricolage Grotesque', category: 'display' },

  // ── Serif ──────────────────────────────────────────────────────────────
  { family: 'Playfair Display', category: 'serif' },
  { family: 'Merriweather', category: 'serif' },
  { family: 'Lora', category: 'serif' },
  { family: 'PT Serif', category: 'serif' },
  { family: 'Noto Serif', category: 'serif' },
  { family: 'Roboto Slab', category: 'serif' },
  { family: 'Bitter', category: 'serif' },
  { family: 'Crimson Text', category: 'serif' },
  { family: 'Cormorant Garamond', category: 'serif' },
  { family: 'Cormorant', category: 'serif' },
  { family: 'EB Garamond', category: 'serif' },
  { family: 'Libre Baskerville', category: 'serif' },
  { family: 'Source Serif Pro', category: 'serif' },
  { family: 'Source Serif 4', category: 'serif' },
  { family: 'Frank Ruhl Libre', category: 'serif' },
  { family: 'Spectral', category: 'serif' },
  { family: 'Fraunces', category: 'serif' },
  { family: 'DM Serif Display', category: 'serif' },
  { family: 'DM Serif Text', category: 'serif' },
  { family: 'Zilla Slab', category: 'serif' },
  { family: 'Bodoni Moda', category: 'serif' },
  { family: 'Newsreader', category: 'serif' },
  { family: 'Instrument Serif', category: 'serif' },
  { family: 'Petrona', category: 'serif' },
  { family: 'Prata', category: 'serif' },
  { family: 'Marcellus', category: 'serif' },
  { family: 'Cardo', category: 'serif' },
  { family: 'Vollkorn', category: 'serif' },
  { family: 'Alegreya', category: 'serif' },
  { family: 'Josefin Slab', category: 'serif' },
  { family: 'IBM Plex Serif', category: 'serif' },
  { family: 'Noticia Text', category: 'serif' },

  // ── Display ────────────────────────────────────────────────────────────
  { family: 'Oswald', category: 'display' },
  { family: 'Bebas Neue', category: 'display' },
  { family: 'Anton', category: 'display' },
  { family: 'Archivo Black', category: 'display' },
  { family: 'Righteous', category: 'display' },
  { family: 'Abril Fatface', category: 'display' },
  { family: 'Comfortaa', category: 'display' },
  { family: 'Fjalla One', category: 'display' },
  { family: 'Teko', category: 'display' },
  { family: 'Syne', category: 'display' },
  { family: 'Unbounded', category: 'display' },
  { family: 'Clash Display', category: 'display' },
  { family: 'Baloo 2', category: 'display' },
  { family: 'Fredoka', category: 'display' },
  { family: 'Chewy', category: 'display' },
  { family: 'Lilita One', category: 'display' },
  { family: 'Titan One', category: 'display' },
  { family: 'Passion One', category: 'display' },
  { family: 'Alfa Slab One', category: 'display' },
  { family: 'Bungee', category: 'display' },
  { family: 'Staatliches', category: 'display' },
  { family: 'Monoton', category: 'display' },
  { family: 'Rowdies', category: 'display' },
  { family: 'Rampart One', category: 'display' },
  { family: 'Shrikhand', category: 'display' },
  { family: 'Yeseva One', category: 'display' },
  { family: 'Philosopher', category: 'display' },
  { family: 'Sacramento', category: 'handwriting' },

  // ── Handwriting / script ───────────────────────────────────────────────
  { family: 'Pacifico', category: 'handwriting' },
  { family: 'Dancing Script', category: 'handwriting' },
  { family: 'Caveat', category: 'handwriting' },
  { family: 'Great Vibes', category: 'handwriting' },
  { family: 'Satisfy', category: 'handwriting' },
  { family: 'Kaushan Script', category: 'handwriting' },
  { family: 'Lobster', category: 'handwriting' },
  { family: 'Cookie', category: 'handwriting' },
  { family: 'Parisienne', category: 'handwriting' },
  { family: 'Allura', category: 'handwriting' },
  { family: 'Pinyon Script', category: 'handwriting' },
  { family: 'Tangerine', category: 'handwriting' },
  { family: 'Marck Script', category: 'handwriting' },
  { family: 'Yellowtail', category: 'handwriting' },
  { family: 'Courgette', category: 'handwriting' },

  // ── Monospace ──────────────────────────────────────────────────────────
  { family: 'JetBrains Mono', category: 'mono' },
  { family: 'Roboto Mono', category: 'mono' },
  { family: 'Space Mono', category: 'mono' },
  { family: 'IBM Plex Mono', category: 'mono' },
  { family: 'Fira Code', category: 'mono' },
  { family: 'Source Code Pro', category: 'mono' },
  { family: 'DM Mono', category: 'mono' },
];

/** All family names (for validation / quick lookup). */
export const GOOGLE_FONT_NAMES = GOOGLE_FONTS.map((f) => f.family);
