// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ixiafbgaqszlokmzjjio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4aWFmYmdhcXN6bG9rbXpqamlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTg2NTEsImV4cCI6MjA3MzY3NDY1MX0.T4d68cj4AemNR8ASKLL5c7tSBPciixeyyVloBgXz1l8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);