/**
 * FINAL campaign — every string in both languages, one source of truth.
 * Each composition takes { lang } and reads from here; rendering the whole
 * campaign in the other language is just a --props change.
 */
import { z } from 'zod';

export const langSchema = z.object({ lang: z.enum(['en', 'sq']) });
export type Lang = 'en' | 'sq';
export const langDefaults: { lang: Lang } = { lang: 'sq' };

export const COPY = {
  en: {
    fr1: {
      hook1: 'Your Instagram is already a shop.',
      hook2: "It just doesn't know it yet.",
      chapters: ['SYSTEM', 'SHOP', 'MONEY', 'CONTROL'],
      ch1cap: 'The system reads your post…',
      ch2cap: 'Your brand. One link.',
      ch3cap: 'Card or cash — any currency.',
      ch4cap: 'Orders, stock, revenue — live.',
      payoff1: 'It all clicks together.',
      payoff2: 'By itself.',
      cta: 'Try free → vela.al',
      trial: '7, 14 or 30 days — you choose.',
    },
    fr2: {
      hook1: 'Opening an online shop?',
      hook2: "You DON'T need:",
      beats: [
        ['A developer', '👨‍💻'],
        ['A designer', '🎨'],
        ['Excel', '📊'],
        ['A warehouse app', '📦'],
        ['A bank visit', '🏦'],
      ] as Array<[string, string]>,
      payoff1: 'You need your Instagram.',
      payoff2: "That's it.",
      cta: 'Start free → vela.al',
    },
    fr3: {
      line1: "You're asleep.",
      line2: "Your shop isn't.",
      trust: 'Card payments, bank-secured.',
      payoff1: 'Open 24/7.',
      payoff2: "Even when you're not.",
      cta: 'Try free → vela.al',
    },
    frc1: { title1: 'From a post', title2: 'to a paid order.', watch: 'Watch how ▶' },
    fp1: {
      hook: 'One screen runs the whole shop.',
      rail: ['Orders', 'Stock', 'Money', 'Brand'],
      payoff1: 'Everything.',
      payoff2: 'One panel.',
      cta: 'See it live → vela.al',
    },
    fp2: {
      hook: 'Shop. Live. 5 minutes.',
      steps: [
        ['Connect Instagram', '30 sec'],
        ['The system builds your products', '3 min'],
        ['Publish & share the link', '90 sec'],
      ] as Array<[string, string]>,
      done: 'LIVE.',
      cta: 'Start now → vela.al',
    },
    frc1eyebrow: 'How it works',
    series: [
      { label: '01 — The system', h1: 'Same post.', h2: 'Now it sells.', sub: 'The system reads the post — name, price, sizes. By itself.', cta: 'Try free → vela.al' },
      { label: '02 — The shop', h1: 'Your brand.', h2: 'One link.', sub: 'Colors, language, look — all yours.', cta: 'Build yours → vela.al' },
      { label: '03 — Payments', h1: 'Card. Cash.', h2: 'Any currency.', sub: 'Bank-secured by RaiAccept · Raiffeisen Bank.', cta: 'Sell safely → vela.al' },
      { label: '04 — Control', h1: 'Everything under', h2: 'control.', sub: 'Orders, stock, revenue — one panel.', cta: 'See it live → vela.al' },
      { label: '05 — The harbor', h1: 'Start', h2: 'free.', sub: '7, 14 or 30 days — you choose.', cta: 'Start now → vela.al' },
    ] as Array<{ label: string; h1: string; h2: string; sub: string; cta: string }>,
    storyEyebrow1: 'Free trial',
    storyEyebrow2: 'Open 24/7',
    car: {
      eyebrow: 'THE VOYAGE OF ONE POST',
      s1head1: 'Every post you make',
      s1head2: 'is a shop that never opened.',
      swipe: 'swipe →',
      s2label: '01 · SYSTEM',
      s2head: 'The system builds the product.',
      s2sub: 'You just posted.',
      s3label: '02 · SHOP',
      s3head: 'Your brand. One link.',
      s3chips: ['SQ / EN', 'Light / Dark', 'Card + Cash', 'L € $ £'],
      s4label: '03 · CONTROL',
      s4head: 'Orders, stock, money — one panel.',
      s5label: 'THE HARBOR',
      s5head: 'Start free.',
      tiers: [
        ['Business', '7 days'],
        ['Pro', '14 days'],
        ['Starter', '30 days'],
      ] as Array<[string, string]>,
      s5note: 'Same app. Full power.',
      cta: 'vela.al',
    },
    fst1: {
      head1: 'Choose how',
      head2: 'you start.',
      tiers: [
        ['Business', '7 days free'],
        ['Pro', '14 days free'],
        ['Starter', '30 days free'],
      ] as Array<[string, string]>,
      note: 'Same app. Full power. No card tricks.',
      tap: 'tap the link ↓',
      ghost: 'link sticker goes here',
    },
    fst2: {
      head: 'While you sleep tonight:',
      checks: ['Orders come in', 'Stock counts itself', 'Cards get charged', 'Totals ready at 7:00'],
      tap: 'tap the link ↓',
      ghost: 'link sticker goes here',
    },
  },
  sq: {
    fr1: {
      hook1: 'Instagrami yt është tashmë dyqan.',
      hook2: "Thjesht s'e di ende.",
      chapters: ['SISTEMI', 'DYQANI', 'PAGESAT', 'KONTROLLI'],
      ch1cap: 'Sistemi po e lexon postimin…',
      ch2cap: 'Marka jote. Një link.',
      ch3cap: 'Me kartë ose kesh — në çdo monedhë.',
      ch4cap: 'Porosi, stok, të ardhura — live.',
      payoff1: 'Gjithçka lidhet bashkë.',
      payoff2: 'Vetë.',
      cta: 'Provo falas → vela.al',
      trial: '7, 14 ose 30 ditë — ti zgjedh.',
    },
    fr2: {
      hook1: 'Po hap dyqan online?',
      hook2: 'NUK të duhet:',
      beats: [
        ['Programues', '👨‍💻'],
        ['Dizajner', '🎨'],
        ['Excel-i', '📊'],
        ['Aplikacion magazine', '📦'],
        ['Radha në bankë', '🏦'],
      ] as Array<[string, string]>,
      payoff1: 'Të duhet vetëm Instagrami.',
      payoff2: 'Kaq.',
      cta: 'Fillo falas → vela.al',
    },
    fr3: {
      line1: 'Ti fle.',
      line2: 'Dyqani jo.',
      trust: 'Pagesa me kartë, të siguruara nga banka.',
      payoff1: 'Hapur 24/7.',
      payoff2: "Edhe kur ti s'je.",
      cta: 'Provo falas → vela.al',
    },
    frc1: { title1: 'Nga postimi', title2: 'te pagesa.', watch: 'Shiko si ▶' },
    fp1: {
      hook: 'Një ekran drejton gjithë dyqanin.',
      rail: ['Porositë', 'Stoku', 'Paratë', 'Marka'],
      payoff1: 'Gjithçka.',
      payoff2: 'Një panel.',
      cta: 'Shihe vetë → vela.al',
    },
    fp2: {
      hook: 'Dyqani. Online. 5 minuta.',
      steps: [
        ['Lidh Instagramin', '30 sek'],
        ['Sistemi ndërton produktet', '3 min'],
        ['Publiko & ndaj linkun', '90 sek'],
      ] as Array<[string, string]>,
      done: 'GATI.',
      cta: 'Fillo tani → vela.al',
    },
    frc1eyebrow: 'Si funksionon',
    series: [
      { label: '01 — Sistemi', h1: 'I njëjti postim.', h2: 'Tani shet.', sub: 'Sistemi e lexon postimin — emri, çmimi, masat. Vetë.', cta: 'Provo falas → vela.al' },
      { label: '02 — Dyqani', h1: 'Marka jote.', h2: 'Një link.', sub: 'Ngjyrat, gjuha, pamja — të tuat.', cta: 'Ndërtoje tëndin → vela.al' },
      { label: '03 — Pagesat', h1: 'Kartë. Kesh.', h2: 'Çdo monedhë.', sub: 'Të siguruara nga banka me RaiAccept · Raiffeisen Bank.', cta: 'Shit i sigurt → vela.al' },
      { label: '04 — Kontrolli', h1: 'Gjithçka nën', h2: 'kontroll.', sub: 'Porosi, stok, të ardhura — një panel.', cta: 'Shihe vetë → vela.al' },
      { label: '05 — Porti', h1: 'Fillo', h2: 'falas.', sub: '7, 14 ose 30 ditë — ti zgjedh.', cta: 'Fillo tani → vela.al' },
    ] as Array<{ label: string; h1: string; h2: string; sub: string; cta: string }>,
    storyEyebrow1: 'Prova falas',
    storyEyebrow2: 'Hapur 24/7',
    car: {
      eyebrow: 'UDHËTIMI I NJË POSTIMI',
      s1head1: 'Çdo postim yti',
      s1head2: "është një dyqan që s'u hap kurrë.",
      swipe: 'rrëshqit →',
      s2label: '01 · SISTEMI',
      s2head: 'Sistemi e ndërton produktin.',
      s2sub: 'Ti vetëm postove.',
      s3label: '02 · DYQANI',
      s3head: 'Marka jote. Një link.',
      s3chips: ['SQ / EN', 'Light / Dark', 'Kartë + Kesh', 'L € $ £'],
      s4label: '03 · KONTROLLI',
      s4head: 'Porosi, stok, para — një panel.',
      s5label: 'PORTI',
      s5head: 'Fillo falas.',
      tiers: [
        ['Business', '7 ditë'],
        ['Pro', '14 ditë'],
        ['Starter', '30 ditë'],
      ] as Array<[string, string]>,
      s5note: 'I njëjti app. Fuqi e plotë.',
      cta: 'vela.al',
    },
    fst1: {
      head1: 'Zgjidh si',
      head2: 'nis.',
      tiers: [
        ['Business', '7 ditë falas'],
        ['Pro', '14 ditë falas'],
        ['Starter', '30 ditë falas'],
      ] as Array<[string, string]>,
      note: 'I njëjti app. Fuqi e plotë. Pa hile.',
      tap: 'prek linkun ↓',
      ghost: 'linku vendoset këtu',
    },
    fst2: {
      head: 'Sonte, ndërsa ti fle:',
      checks: ['Porositë vijnë', 'Stoku numërohet vetë', 'Kartat paguhen', 'Totali gati në 7:00'],
      tap: 'prek linkun ↓',
      ghost: 'linku vendoset këtu',
    },
  },
} as const;
